# Set base image (host OS)
FROM python:3.8-alpine

# By default, listen on port 5000
EXPOSE 5000/tcp

# Set the working directory in the container
WORKDIR /PassGenApp

# Copy the dependencies file to the working directory
COPY requirements.txt .

# Install any dependencies
RUN apk add g++
RUN pip install -r requirements.txt

# Copy the content of the local src directory to the working directory
#COPY app.py .
#COPY adjectives.csv .
#COPY adverbs.csv .
#COPY animals.csv .
#COPY special.csv .
COPY . /PassGenApp

# Specify the command to run on container start
CMD [ "python", "./app.py" ]